# Generated by Django 5.2.15 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('messages', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
