# Generated by Django 5.2.15 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity', models.IntegerField()),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.JSONField(default=list)),
                ('specs', models.JSONField(default=dict)),
                ('schedules', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'helicopters',
            },
        ),
    ]
