# Generated by Django 5.2.15 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'tours',
            },
        ),
    ]
