# Generated by Django 5.2.15 on 2026-07-04 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='inclusions',
        ),
        migrations.AddField(
            model_name='tour',
            name='exclusions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tour',
            name='inclusions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]

