# Generated by Django 5.2.15 on 2026-07-04 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='schedules',
        ),
        migrations.AddField(
            model_name='boat',
            name='schedules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]

