# Generated by Django 5.2.15 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(default='5.0/5.0', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
    ]
